BAT_SEARCH_QUERIES = {
    "Toyota AE86 Sprinter Trueno AE86": "toyota ae86",
    "Mazda RX-7 FC": "mazda rx-7 fc",
    "Mazda RX-7 FD": "mazda rx-7 fd",
    "Nissan Skyline GT-R R32": "nissan r32 skyline",
    "Nissan Skyline GT-R R33": "nissan r33 skyline",
    "Nissan Skyline GT-R R34": "nissan r34 skyline",
    "Nissan Silvia S13": "silvia",
    "Nissan Silvia S14": "silvia",
    "Nissan Silvia S15": "silvia",
    "Honda S2000 AP1": "honda s2000",
    "Honda S2000 AP2": "honda s2000",
    "Honda Integra Type R DC2": "integra type r",
    "Honda Integra Type R DC5": "integra type r",
    "Toyota Supra A80": "toyota a80 supra",
    "Mitsubishi Lancer Evolution III": "mitsubishi lancer evolution",
    "Mitsubishi Lancer Evolution IV": "mitsubishi lancer evolution",
    "Mitsubishi Lancer Evolution V": "mitsubishi lancer evolution",
    "Mitsubishi Lancer Evolution VI": "mitsubishi lancer evolution",
    "Mitsubishi Lancer Evolution VII": "mitsubishi lancer evolution",
    "Mitsubishi Lancer Evolution VIII": "mitsubishi lancer evolution",
    "Mitsubishi Lancer Evolution IX": "mitsubishi lancer evolution",
    "Subaru Impreza WRX STI GC8": "wrx sti",
    "Subaru Impreza WRX STI GDB": "wrx sti",
    "Mazda MX-5 Miata NA": "mazda na mx-5 miata",
    "Mazda MX-5 Miata NB": "mazda nb mx-5 miata",
    "Toyota GR86 ZN8": "toyota gr86",
    "Subaru BRZ ZD8": "subaru brz",
    "Toyota GR Supra A90": "toyota a90 supra",
    "Mazda MX-5 Miata NC": "mazda nc mx-5 miata",
    "Mazda MX-5 Miata ND": "mazda nd mx-5 miata",
    "Mazda RX-8 SE3P": "mazda rx-8",
    "Honda Civic Type R FK8": "civic type r",
    "Honda Civic Type R FL5": "civic type r",
    "Honda Integra Type S DE5": None,  # no BaT page yet
    "Acura TLX Type S UA3": None,  # no BaT page yet
    "Nissan Z RZ34": "400z",
    "Toyota GR Corolla GZEA14H": None,  # no BaT page yet
    # Phase 2 volume expansion — added 2026-06-14 (verified against BaT auction counts)
    "Datsun 240Z S30": "datsun 240z",
    "Datsun 280Z S30": "datsun 280z",
    "Datsun 280ZX S130": "nissan 280zx",
    "Nissan 300ZX Z31": "nissan 300zx",
    "Nissan 300ZX Z32": "nissan 300zx",
    "Nissan 350Z Z33": "nissan 350z",
    "Nissan 370Z Z34": "nissan 370z",
    "Acura NSX NA1": "acura nsx na1",
    "Acura NSX NA2": "acura nsx na1",
    "Nissan GT-R R35": "nissan gt-r r35",
    "Toyota MR2 SW20": "toyota mr2",
    "Toyota Supra A70": "toyota a70 supra",
    "Lexus SC Z30": "lexus sc300",
    "Mitsubishi 3000GT Z16A": "mitsubishi 3000gt",
    "Honda Prelude BB": "honda prelude",
    "Nissan 240SX S13": "nissan 240sx",
    "Nissan 240SX S14": "nissan 240sx",
    "Honda Civic Si EK": "honda civic ek",
}
