BAT_SEARCH_QUERIES = {
    "Toyota AE86 Sprinter Trueno AE86": "toyota ae86",
    "Mazda RX-7 FC": "mazda rx-7 fc",
    "Mazda RX-7 FD": "mazda rx-7 fd",
    "Nissan Skyline GT-R R32": "nissan r32 skyline",
    "Nissan Skyline GT-R R33": "nissan r33 skyline",
    "Nissan Skyline GT-R R34": "nissan r34 skyline",
    "Nissan Silvia S13": "silvia",
    "Nissan Silvia S14": "silvia",
    "Nissan Silvia S15": "silvia",
    "Honda S2000 AP1": "honda s2000",
    "Honda S2000 AP2": "honda s2000",
    "Honda Integra Type R DC2": "integra type r",
    "Honda Integra Type R DC5": "integra type r",
    "Toyota Supra A80": "toyota a80 supra",
    "Mitsubishi Lancer Evolution III": "mitsubishi lancer evolution",
    "Mitsubishi Lancer Evolution IV": "mitsubishi lancer evolution",
    "Mitsubishi Lancer Evolution V": "mitsubishi lancer evolution",
    "Mitsubishi Lancer Evolution VI": "mitsubishi lancer evolution",
    "Mitsubishi Lancer Evolution VII": "mitsubishi lancer evolution",
    "Mitsubishi Lancer Evolution VIII": "mitsubishi lancer evolution",
    "Mitsubishi Lancer Evolution IX": "mitsubishi lancer evolution",
    "Subaru Impreza WRX STI GC8": "wrx sti",
    "Subaru Impreza WRX STI GDB": "wrx sti",
    "Mazda MX-5 Miata NA": "mazda na mx-5 miata",
    "Mazda MX-5 Miata NB": "mazda nb mx-5 miata",
    "Toyota GR86 ZN8": "toyota gr86",
    "Subaru BRZ ZD8": "subaru brz",
    "Toyota GR Supra A90": "toyota a90 supra",
    "Mazda MX-5 Miata NC": "mazda nc mx-5 miata",
    "Mazda MX-5 Miata ND": "mazda nd mx-5 miata",
    "Mazda RX-8 SE3P": "mazda rx-8",
    "Honda Civic Type R FK8": "civic type r",
    "Honda Civic Type R FL5": "civic type r",
    "Honda Integra Type S DE5": None,  # no BaT page yet
    "Acura TLX Type S UA3": None,  # no BaT page yet
    "Nissan Z RZ34": "400z",
    "Toyota GR Corolla GZEA14H": None,  # no BaT page yet
}
