-- Per-car hero photos from Wikimedia Commons (replaces BaT thumbnails).
-- Every Commons license we accept (CC0 / PD / CC BY / CC BY-SA) is shown with
-- author + license + source link; the site applies a duotone filter, so credits
-- are marked "(edited)".
--
-- Run in the Supabase SQL editor. Then paste the UPDATE statements generated by
-- the photo-picker contact sheet (project_artifacts/jdm-market-tracker/commons).

alter table cars
  add column if not exists image_url         text,
  add column if not exists image_author      text,
  add column if not exists image_license     text,
  add column if not exists image_license_url text,
  add column if not exists image_source_url  text;
